### ISSUE TITLE
Feature Request: Add Functionality to Convert content:// URIs to File Paths

### ISSUE THREAD

**Issue by lorenzolanciok** [SNNafi/media_store_plus#13]
Hello!
I am currently using your media_store_plus library in my Flutter project and have found it extremely useful for handling media files. However, I have encountered a limitation that I believe could be a valuable addition to your library.

Feature Description:
I would like to request a feature that enables the conversion of content:// URIs to actual file system paths. As of now, the library provides content:// URIs for media files, but there's no straightforward way to convert these URIs into file paths within Flutter.

Use Case:
In my application, I am retrieving media files using media_store_plus, which returns the media in the form of content:// URIs. For specific operations, I need to access the actual file path. This is a common scenario for apps that need more direct interaction with the file system.

Proposed Solution:
It would be immensely helpful if media_store_plus could include a method to convert content:// URIs to file paths. This function could either be a direct URI-to-path conversion method or an enhancement in the existing file retrieval methods to include an option to obtain the file path directly.

Thank you for considering this feature request. I am looking forward to any updates on this and would be happy to contribute to the discussion if needed.

Best regards,
Lorenzo

**Comment by SheepYang1993** [comment]
I also have the same situation, if I could provide convert content:// URIs to file paths, it would be really helpful!

**Comment by SNNafi** [comment]
Added in the latest release i.e. `0.1.0`
