### ISSUE TITLE
How to not crash in a shared iOS/Android project?

### ISSUE THREAD

**Issue by kajensen** [SNNafi/media_store_plus#15]
Receiving this error when following the example code:

`flutter: MissingPluginException(No implementation found for method getPlatformSDKInt on channel media_store_plus)`

 Any help would be appreciated

**Comment by kajensen** [comment]
I modified the MediaStore init to avoid this crash. See my fork:
https://github.com/kajensen/media_store_plus

You'll need to manually call the getPlatformSDKInt method if not on Android.
Can send pull request if necessary

**Comment by SNNafi** [comment]
You can conditionally call the constructor.  Like,

```dart
late final MediaStore mediaStorePlugin;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  if (Platform.isAndroid) {
    mediaStorePlugin = MediaStore();
  }
}
```
