### ISSUE TITLE
Make mediaStore.saveFile return file URI (with content:// scheme)

### ISSUE THREAD

**Issue by Henry-Hiles** [SNNafi/media_store_plus#18]
It would be much appreciated if saveFile could return the file URI when I save the file. Thank you!

**Comment by SNNafi** [comment]
@Henry-Hiles, Just finished this. Will release soon within 3-4 days

**Comment by Henry-Hiles** [comment]
> @Henry-Hiles, Just finished this. Will release soon within 3-4 days

Thank you so much!

**Comment by SNNafi** [comment]
Released

**Comment by Henry-Hiles** [comment]
> Released

I've just realized this isn't what I want

**Comment by Henry-Hiles** [comment]
As you can see from the title, i said content:// scheme, not file://, also it would be better if it was a Uri not String. Thanks!

**Comment by SNNafi** [comment]
It is `content:// scheme`. You can create a `Uri` object from the Uri String i.e. `Uri.parse(uri)`

Here is my console result after saving,

```shell
D/saveFile( 9771): al_aqsa_mosque.jpeg
I/flutter ( 9771): content://media/external/images/media/1000000073 <- returned by saveFile()
```

**Comment by Henry-Hiles** [comment]
> It is `content:// scheme`. You can create a `Uri` object from the Uri String i.e. `Uri.parse(uri)`
> 
> Here is my console result after saving,
> 
> ```shell
> D/saveFile( 9771): al_aqsa_mosque.jpeg
> I/flutter ( 9771): content://media/external/images/media/1000000073 <- returned by saveFile()
> ```

Oh huh, I just realized its returning null for me, is that normal?

**Comment by Henry-Hiles** [comment]
Also this should be updated:
![image](https://github.com/SNNafi/media_store_plus/assets/71790868/3111b4a7-d0bd-4f98-9b01-95bfcb50f592)

**Comment by Henry-Hiles** [comment]
> > It is `content:// scheme`. You can create a `Uri` object from the Uri String i.e. `Uri.parse(uri)`
> > Here is my console result after saving,
> > ```shell
> > D/saveFile( 9771): al_aqsa_mosque.jpeg
> > I/flutter ( 9771): content://media/external/images/media/1000000073 <- returned by saveFile()
> > ```
> 
> Oh huh, I just realized its returning null for me, is that normal?

Ah, I guess that means it failed. Hmm. Clearing out my downloads fixed it, but not ideal.

**Comment by Henry-Hiles** [comment]
Okay, it returns null, if a file with the same name in the same place was generated by a different app...

**Comment by SNNafi** [comment]
It should ask for permission to overwrite the file. Like this,

<img src="https://github.com/SNNafi/media_store_plus/assets/22527366/f16afab4-e545-49e7-9250-3ab62d62cd14" alt="screenshot" height="300"/>

**Comment by Henry-Hiles** [comment]
It doesn't do that for me or any testers of my app, hmm

**Comment by Henry-Hiles** [comment]
If it's overwriting a file created by this app, it overrides without confirmation (that's fine), but if another app created it it returns null.

**Comment by SNNafi** [comment]
You need to add these permission to manifest for reading respective media types,

```xml
    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
    <uses-permission android:name="android.permission.READ_MEDIA_AUDIO" />
    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
```

Then only the app checks for existing files and asks for overwriting. I didn't allow the permissions and it returns `null`.

```shell
D/DisplayName al %aqsa_mosque.jpeg(13124): null <- can't read the file as no permission is allowed.
D/saveFile(13124): al %aqsa_mosque.jpeg
I/flutter (13124): null ->  Can't save the file as __al %aqsa_mosque.jpeg__ as there's already a file exists. so returned null
```
But the file is saved as __al %aqsa_mosque (1).jpeg__. It is done by media store API by default.

**Comment by Henry-Hiles** [comment]
> You need to add these permission to manifest for reading respective media types,
> 
> ```
>     <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
>     <uses-permission android:name="android.permission.READ_MEDIA_AUDIO" />
>     <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
> ```
> 
> Then only the app checks for existing files and asks for overwriting. I didn't allow the permissions and it returns `null`.
> 
> ```shell
> D/DisplayName al %aqsa_mosque.jpeg(13124): null <- can't read the file as no permission is allowed.
> D/saveFile(13124): al %aqsa_mosque.jpeg
> I/flutter (13124): null ->  Can't save the file as __al %aqsa_mosque.jpeg__ as there's already a file exists. so returned null
> ```
> 
> But the file is saved as **al %aqsa_mosque (1).jpeg**. It is done by media store API by default.

Hmm, I'm saving to the downloads folder. It can be any type of file, what should I add to manifest? Altetnatively, returning the URI of the `(1)` file if its created would be even better!

**Comment by SNNafi** [comment]
However, __you don't need to add these permissions to read and write the files created by your app__. 
Again if you __uninstalled__ your app, the files your app is created will be treated as __another app creates it__, the next time you install your app.

**Comment by Henry-Hiles** [comment]
> However, **you don't need to add these permissions to read and write the files created by your app**. Again if you **uninstalled** your app, the files your app is created will be treated as **another app creates it**, the next time you install your app.

Yes I see thanks

**Comment by SNNafi** [comment]
You can ask for permission to read the `Downloads/<AnyFolder>` folder using 
```dart
Future<DocumentTree?> requestForAccess({required String? initialRelativePath})
```
this method. There's an example [here](https://github.com/SNNafi/media_store_plus/blob/4f5e47a013acdf0f640dea38a764bee4e575346b/example/lib/util.dart#L38)

**Comment by Henry-Hiles** [comment]
> You can ask for permission to read the `Downloads/<YourAppFolder>` folder using
> 
> ```dart
> Future<DocumentTree?> requestForAccess({required String? initialRelativePath})
> ```
> 
> this method. There's an example [here](https://github.com/SNNafi/media_store_plus/blob/4f5e47a013acdf0f640dea38a764bee4e575346b/example/lib/util.dart#L38)

I see. And I need to have read access to overwrite the files? Would it be possible to return the uri with the (1) instead, if that's the one created? Thanks!!

**Comment by SNNafi** [comment]
> > You can ask for permission to read the `Downloads/<YourAppFolder>` folder using
> > ```dart
> > Future<DocumentTree?> requestForAccess({required String? initialRelativePath})
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > this method. There's an example [here](https://github.com/SNNafi/media_store_plus/blob/4f5e47a013acdf0f640dea38a764bee4e575346b/example/lib/util.dart#L38)
> 
> I see. And I need to have read access to overwrite the files? Would it be possible to return the uri with the (1) instead, if that's the one created? Thanks!!

No, that's not ideal behavior. It can be (1), (2) or who knows? Again `null` can be also returned if there is an actual issue. So. this is not possible.

But you can always check by using 

```dart
Future<Uri?> getFileUri({
    required String fileName,
    required DirType dirType,
    required DirName dirName,
    String? relativePath,
  })
```
Here the fileName would be `al %aqsa_mosque (1).jpeg`

But it's better to ask for access as it is the standard approach. Users don't like to add duplicated files to the devices.

**Comment by Henry-Hiles** [comment]
> > > You can ask for permission to read the `Downloads/<YourAppFolder>` folder using
> > > ```dart
> > > Future<DocumentTree?> requestForAccess({required String? initialRelativePath})
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > this method. There's an example [here](https://github.com/SNNafi/media_store_plus/blob/4f5e47a013acdf0f640dea38a764bee4e575346b/example/lib/util.dart#L38)
> > 
> > 
> > I see. And I need to have read access to overwrite the files? Would it be possible to return the uri with the (1) instead, if that's the one created? Thanks!!
> 
> No, that's not ideal behavior. It can be (1), (2) or who knows? Again `null` can be also returned if there is an actual issue. So. this is not possible.
> 
> But you can always check by using
> 
> ```dart
> Future<Uri?> getFileUri({
>     required String fileName,
>     required DirType dirType,
>     required DirName dirName,
>     String? relativePath,
>   })
> ```
> 
> Here the fileName would be `al %aqsa_mosque (1).jpeg`
> 
> But it's better to ask for access as it is the standard approach. Users don't like to add duplicated files to the devices.

What I meant was on the library side, if it's saved with a number, could you return the uri of that instead of null?

**Comment by SNNafi** [comment]
I want to stick with the standard way i.e. asking for request access.

**Comment by Henry-Hiles** [comment]
> I want to stick with the standard way i.e. asking for request access.

Well, if the file is being saved, surely the uri should be returned? Even if its under a different filename. This is how a browser would work, it'd save that way and still have an open option.

**Comment by SNNafi** [comment]
`saveFile()` now returns `SaveInfo`. It contains the saved file name, uri and the saved status, whether the file is created, replaced or duplicated


Check here: https://github.com/SNNafi/media_store_plus/blob/main/lib/src/save_info.dart

Available from `0.1.1`

**Comment by Henry-Hiles** [comment]
Thank you!

**Comment by Henry-Hiles** [comment]
> `saveFile()` now returns `SaveInfo`. It contains the saved file name, uri and the saved status, whether the file is created, replaced or duplicated
> 
> Check here: https://github.com/SNNafi/media_store_plus/blob/main/lib/src/save_info.dart
> 
> Available from `0.1.1`

With latest release it no longer duplicates the file, instead throwing a PathAccessException saying it cannot copy the file

**Comment by Henry-Hiles** [comment]
And then i tried it again and it worked? Hmm.

**Comment by Henry-Hiles** [comment]
Yep it seems to work now, thanks!

**Comment by Henry-Hiles** [comment]
Hmm... The save info is only returned on debug, not release builds.

**Comment by SNNafi** [comment]
Working fine. Checked on the release build. I don't know how you are testing things!
