### ISSUE TITLE
MediaStore.saveFile.uri return null only on release mode

### ISSUE THREAD

**Issue by dimaskris98** [SNNafi/media_store_plus#21]
Hello. I need help for this issue.

i use your plugin to save my file to download folder.
this is my code

    if(mediaStore == null){
      mediaStore = MediaStore();
    }

    MediaStore.appFolder = "Digital Office";

    Directory directory = await getApplicationSupportDirectory();
    File tempFile = File("${directory.path}/$fileName");
    tempFile.writeAsBytesSync(file.readAsBytesSync());

      final SaveInfo? saveInfo = await mediaStore!.saveFile(
        tempFilePath: tempFile.path,
        dirType: DirType.download,
        dirName: DirType.download.defaults,
      );

      if(saveInfo != null){
        var uri = saveInfo!.uri.toString();
        fileLocation = (await mediaStore!.getFilePathFromUri(uriString: uri))!;
      }else{
        fileLocation = null;
      }

    return fileLocation;

this code works well when i run it on debug mode both on emulator and real device.
but if i build the app on release mode, saveInfo.uri return null on API 30 above. 

can you fix this issue.
Thanks you

**Comment by Henry-Hiles** [comment]
I had this same issue, its now replaced by another issue. I'm going to try and fix it and then PR.

**Comment by Henry-Hiles** [comment]
> Hello. I need help for this issue.
> 
> i use your plugin to save my file to download folder. this is my code
> 
> ```
> if(mediaStore == null){
>   mediaStore = MediaStore();
> }
> 
> MediaStore.appFolder = "Digital Office";
> 
> Directory directory = await getApplicationSupportDirectory();
> File tempFile = File("${directory.path}/$fileName");
> tempFile.writeAsBytesSync(file.readAsBytesSync());
> 
>   final SaveInfo? saveInfo = await mediaStore!.saveFile(
>     tempFilePath: tempFile.path,
>     dirType: DirType.download,
>     dirName: DirType.download.defaults,
>   );
> 
>   if(saveInfo != null){
>     var uri = saveInfo!.uri.toString();
>     fileLocation = (await mediaStore!.getFilePathFromUri(uriString: uri))!;
>   }else{
>     fileLocation = null;
>   }
> 
> return fileLocation;
> ```
> 
> this code works well when i run it on debug mode both on emulator and real device. but if i build the app on release mode, saveInfo.uri return null on API 30 above.
> 
> can you fix this issue. Thanks you

You can use my fork: https://github.com/Henry-Hiles/media_store_plus, it has a fix (albeit a janky one)

**Comment by Henry-Hiles** [comment]
Find android/app/proguard-rules.pro, and add `-keep class com.snnafi.media_store_plus.SaveInfo { <fields>; }` to it.

**Comment by SNNafi** [comment]
Nice findings. Can you please give a PR?

**Comment by Henry-Hiles** [comment]
> Nice findings. Can you please give a PR?

Hmm, I put the proguard rule in my project, not media store plus. Is it possible to add a proguard rule directly to the lib? (I added the rule to my app that uses media_store_plus)

**Comment by Henry-Hiles** [comment]
Also I probably will be PRing another fix that causes issues that cause exceptions when saving a file, but its a breaking change, is that okay?

**Comment by SNNafi** [comment]
Can you please explain the issue? Please create another issue for the later one.

**Comment by Henry-Hiles** [comment]
> Can you please explain the issue? Please create another issue for the later one.

Basically on release mode, proguard (in the app using media_store_plus) wiil attempt to minify everything, so it changes json names to just be "a", "b", "c", instead of "name", "uri", "save_status" (this is in SaveInfo.kt). So, that breaks the code. To fix this, we completely ignore that file, and tell it dont minify the fields. (a slightly more janky fix is to change save_info.dart to use "a", "b", and "c" as backups)

**Comment by SNNafi** [comment]
Not this one. The breaking issue.

**Comment by Henry-Hiles** [comment]
The breaking issue (which to be clear is not what this issue is about), is caused by the sdkInt being initialized late, so the first saveFile assumes sdkInt is 0, causing unexpected behavior and permission errors. I fixed this by making the MediaStore constructor private, and adding a .create() async method, which returns an instance of MediaStore.

**Comment by Henry-Hiles** [comment]
You can see my changes here: https://github.com/SNNafi/media_store_plus/compare/main...Henry-Hiles:media_store_plus:main#diff-bf1183ed13dadbadb90cf5464590b8e85b35fc7753a502bdb7c4e19d298643fd

**Comment by SNNafi** [comment]
@Henry-Hiles  Sorry fo the late reply. I have also thought about this.
Add a new static method like `WidgetsFlutterBinding.ensureInitialized()`

First call the `await MediaStore.ensureInitialized()`. You are good to go.

Available in the latest version.

**Comment by SNNafi** [comment]
@dimaskris98 , please modify the `proguard-rules.pro` as per @Henry-Hiles  reply. You can also add from [this](https://github.com/google/gson/blob/main/examples/android-proguard-example/proguard.cfg) link which is more future-proof.

Also added in the README.md

**Comment by dimaskris98** [comment]
Sorry for my late reply. i will try it on my next patch and inform it to you. 

Thanks you.
