### ISSUE TITLE
requestForAccess(initialRelativePath: initialRelativePath) prompts for permission even if it was already allowed

### ISSUE THREAD

**Issue by bettkipronoh** [SNNafi/media_store_plus#22]
Thanks for the great plugin.

`MediaStorePlatform.instance
        .requestForAccess(initialRelativePath: initialRelativePath)` Prompts user always even if the user allowed it already. Is there a way to check it and if allowed get the Ducumenttree?

**Comment by SNNafi** [comment]
The prompt happens automatically by the os. We have no control over it.

BUT, You can use this method to check if it is allowed or not. 
https://github.com/SNNafi/media_store_plus/blob/4b761d0f872a3c3fe85717d29061c1d29d7933a5/lib/media_store_plus.dart#L343C1-L348C1

**Comment by bettkipronoh** [comment]
@SNNafi But if i use the method am getting exception 
` java.lang.IllegalArgumentException: Invalid URI: file:///storage/emulated/0/Android/media/com.xx/xxxx/xxxx/.xxxx/
E/getFolderChildren(25151): 	at android.provider.DocumentsContract.getTreeDocumentId(DocumentsContract.java:1278)
E/getFolderChildren(25151): 	at androidx.documentfile.provider.DocumentFile.fromTreeUri(DocumentFile.java:136)
E/getFolderChildren(25151): 	at com.snnafi.media_store_plus.MediaStorePlusPlugin.getFolderChildren(MediaStorePlusPlugin.kt:678)
E/getFolderChildren(25151): 	at com.snnafi.media_store_plus.MediaStorePlusPlugin.onMethodCall(MediaStorePlusPlugin.kt:137)`
While `getUriFromFilePath` returns null while am sure the path exists.
