### ISSUE TITLE
🐛 requestForAccess() doesn't open in initialRelativePath location - sdk 33+

### ISSUE THREAD

**Issue by tempo-riz** [SNNafi/media_store_plus#24]
```final documentTree = await mediaStorePlugin.requestForAccess(initialRelativePath: "Android/media");```

File picker is not opened at initialRelativePath

I also tried with Download/Folder1 same result

**Comment by SNNafi** [comment]
This is an experimental API.  The underlying Native API is deprecated for `initialRelativePath` & may not work. 
I have updated the doc
