### ISSUE TITLE
Issue with PDF/XML/JSON/... File Management and Scoped Storage Limitations

### ISSUE THREAD

**Issue by Jakuzeisme** [SNNafi/media_store_plus#28]
# Issue with PDF/XML/JSON File Management and Scoped Storage Limitations

First of all, thanks for this package – it’s been incredibly helpful in navigating the complex storage policies. Android’s storage policies are really becoming tough to keep up with, even for developers. Android needs to find a better way to handle file access and storage.

My app manages non-media files (like PDF, XML, and JSON), creating and editing them as part of its core functionality. Unfortunately, due to the storage limitations and the fact that I can’t directly access these file locations, I’ve had to use a file picker to copy files into a directory I created at `Download/myfileeditor/`. This approach:
   - Increases storage use since files are duplicated instead of simply accessed.
   - Reduces app performance due to the extra handling required for file management.

And I'm having a hard time properly figuring out which permissions to use for app the android versions.
Because of these restrictions, I haven’t been able to publish my app, even though I’ve spent years working on it. This has been frustrating, and any guidance you could offer on a better way to manage files in this context would be greatly appreciated.

Also, if I understand correctly, if the user uninstalls and reinstalls my app, it will lose read/write access to the `myfileeditor` folder that my app initially created. This could cause serious issues with user data continuity. Do you have any recommendations on handling this aspect effectively? It’s been tough to work around, and I'm looking for any possible solutions.

Thanks again, and I’d appreciate any advice or potential updates that could help resolve these issues.
Also if you want to see my current setup pls ask, I will gladly share it.
And once we are done I think we need to put examples in the pubdev page for non media api and media api so devs can just copy and paste instead of wasting time setting up permissions

**Comment by SNNafi** [comment]
Please create an issue, if you have any problems regarding this package. 

Otherwise, there is StackOverflow, Reddit. Please post your query there. There are more experience and better developers. You can even ask chatgpt. 

Thank you

**Comment by Jakuzeisme** [comment]
Yo @SNNafi obviously  I've tried other things before coming here to ask, u don't need to be so dismissive and you're assuming a lot
You can ask chatgpt and see the response it comes up with.
I guess if you do not answer...just answer this
Can this package work for non media files?


And BTW there's nothing useful on stackoverflow, look at the exact question  here
https://stackoverflow.com/questions/76999561/how-to-save-file-to-downloads-folder-on-android-33

If you got the experience the community needs your help, doesn't need to be code just a quick summary of the best approach you can think it
Simple

**Comment by Jakuzeisme** [comment]
It's all bout perspective.
And BTW  this question is not unrelated.
I read the motivation for this pkg and they alighn

**Comment by Jakuzeisme** [comment]
Bro come on
Dev to dev

**Comment by SNNafi** [comment]
_Can this package work for non-media files?_

- Yes, it can. There's an [example](https://github.com/SNNafi/media_store_plus/blob/main/example/lib/util.dart) available.
- I maintain this package in my free time. It includes detailed documentation and an example project. __Since you're asking this question, it seems you haven't yet tried running the example__.

_If you got the experience the community needs your help, doesn't need to be code just a quick summary of the best approach you can think it._

- Yes, there’s documentation and an example project for that.
- This package was developed because I encountered this problem myself. So I tried to help the community. However, that doesn’t mean I need to answer questions that can be resolved by simply using the package or any questions other than any bugs of the package. 


Sorry if this sounds rude, but I have my chores to do.

**Comment by Jakuzeisme** [comment]
You get lucky say u answer, I for open another issue
Alaye😂😂

**Comment by Jakuzeisme** [comment]
Yo! 
Please answer me this.
I noticed in android 13 I can't access folders in public download directory created by my app before uninstallation.
Is there any work around around this to be able to access this?

**Comment by Jakuzeisme** [comment]
Yo! 
Please answer me this.
I noticed in android 13 I can't access folders in public download directory created by my app before uninstallation.
Is there any work around around this to be able to access this?

**Comment by Jakuzeisme** [comment]
Yo! 
Please answer me this.
I noticed in android 13 I can't access folders in public download directory created by my app before uninstallation.
Is there any work around around this to be able to access this?

**Comment by SNNafi** [comment]
No
