### ISSUE TITLE
Save to desired location with saveFile function

### ISSUE THREAD

**Issue by HasancanCakicioglu** [SNNafi/media_store_plus#29]
The problem is that the user has chosen android, dcim or another folder. I get permission to the selected location with 'requestForAccess' but when I want to save my file to the selected location with saveFile, it saves it under downloads. But editFile works fine, I can update it after selecting it with 'requestForAccess'. Although I couldn't try it outside the downloads folder.

You can see the code I used below, I think the problem is
dirType: DirType.download,dirName: DirName.download,
in this part, but I want to determine it according to the incoming uri. So is there a way to save it as whatever the uri is without manually setting it as download or dcmi?

```
  Future<void> backupDatabase() async {
    // MediaStore'u başlat
    await MediaStore.ensureInitialized();
    MediaStore.appFolder = "MediaStorePlugin";
    final mediaStore = MediaStore();

    try {
      
      //String? selectedDirectory = await FilePicker.platform.getDirectoryPath();
      DocumentTree? documentTree =
          await mediaStore.requestForAccess(initialRelativePath: "");

      if (documentTree == null) {
        print("Document tree is null.");
        return;
      }

      final dbPath = await getDatabasePath(); 
      
      final dbFile = File(dbPath);

      if (await dbFile.exists()) {
        try {
   
          final tempDir = await getTemporaryDirectory();
          final tempFilePath = "${tempDir.path}/backup.db";

          await dbFile.copy(tempFilePath);


          bool exists = false;
          String? existingFileUri;
          for (var element in documentTree.children) {
            if (element.name == "backup.db") {
              exists = true;
              existingFileUri = element.uriString;
              break;
            }
          }

          if (exists && existingFileUri != null) {
            bool edited = await mediaStore.editFile(
              uriString: existingFileUri,
              tempFilePath: tempFilePath,
            );
            if (edited) {
              print("File updated successfully.");
            } else {
              print("File could not be updated.");
            }
          } else {
            final saveInfo = await mediaStore.saveFile(
              tempFilePath: tempFilePath,
              dirType: DirType.download,
              dirName: DirName.download,
              relativePath: documentTree.uri.pathSegments.join("/"),
            );

            if (saveInfo != null) {
              print("File saved : ${saveInfo.name}");
            } else {
              print("File could not be saved.");
            }
          }
        } catch (e) {
          print("Database error : $e");
        }
      } else {
        print("Database file not found.");
      }
    } catch (e) {
      print("Folder error: $e");
    }
  }
```

**Comment by SNNafi** [comment]
You are using saveFile method with DirType & DirName as download. So it will be saved in download folder.

You are setting the uri in the relativePath. It doesn't save it in the uri location.

Please check the documentation first.

And currently there is no way to save file using uri. 

Maybe I can add that. I will check this later.

**Comment by HasancanCakicioglu** [comment]
Sorry for bothering you but I also looked at the code but I couldn't find how to save. I can choose the location I want with requestForAccess but I can't save it to the location I choose.

/// Directory Type
enum DirType { photo, audio, video, download }

/// Directory names for directory type.
/// Read more from here: https://developer.android.com/training/data-storage/shared/media#media_store
enum DirName {
dcim,
pictures,
movies,
alarms,
audiobooks,
music,
notifications,
podcasts,
ringtones,
download
}

It is set as above, doesn't this restrict us? For example, if I want to save under the Android folder, I won't be able to. However, with requestForAccess, I can get permission to any location under the Android folder. Is there an inconsistency here or am I misunderstanding?

**Comment by SNNafi** [comment]
Did you read the `README.md` file?

This package primarily aims to use the underlying __Media Store API__. Media Store API only supports these  Directory Types and Directory names. That's why it is called `media_store_plus`

This package does not aim for direct file access or other functions. Again, `requestForAccess` is experimental.
