### ISSUE TITLE
Something wrong in passing on DocumentTree and Document json data from native code

### ISSUE THREAD

**Issue by StephanKimmerle** [SNNafi/media_store_plus#6]
In the file document_tree.dart, I had to correct the .fromJson methods in release mode (it worked without the adjustments in debug mode).
I got the error message: 
**Unhandled Exception: type 'Null' is not a subtype of type 'List<dynamic>' in type cast new DocumentTree.fromJson (package:media_store_plus/src/document_tree.dart:16)**

In the DocumentTree class description, I had to use **json["b"] // instead of json["children"]** 

```
factory DocumentTree.fromJson(dynamic data) {
    final json = jsonDecode(data);
    var children =
        (json["b"] // instead of json["children"] 
        as List<dynamic>).map((e) => Document.fromJson(e)).toList();
    return DocumentTree(uriString: json["uri_string"], children: children);
  }
```

and in the Document class description **data["a"], // instead of data["name"]**
```
  factory Document.fromJson(Map<String, dynamic> data) => Document(
        data["uri_string"],
        data["a"], // instead of data["name"]
        data["is_virtual"],
        data["is_directory"],
        data["file_type"],
        data["last_modified"],
        data["file_length"],
        data["is_writable"],
        data["is_deletable"],
      );
```

**Comment by SNNafi** [comment]
That's a weird one. Let me check. Thanks for pointing that out!

**Comment by SNNafi** [comment]
@StephanKimmerle , Can you please check the new version i.e. __0.0.6__

**Comment by StephanKimmerle** [comment]
Works perfect. Solved the problem!
Thank you for all your work!

**Comment by SNNafi** [comment]
You are most welcome
