### ISSUE TITLE
DocumentTree fromJson

### ISSUE THREAD

**Issue by StephanKimmerle** [SNNafi/media_store_plus#8]
The fromJson method in the class DocumentTree takes _encoded data_ and therefore has to start with **jsonDecode(data)**, see
```
factory DocumentTree.fromJson(dynamic data) {
    final json = jsonDecode(data);
...
}
```
In contrast, the Document.fromJson method takes an unencoded _Map<String, dynamic> data_. 
That's, I believe, the usually expected way to use _fromJson_. 

It would be nice to have this consistent and according to usual norms of the "fromJson" method. 

In addition, it would be nice to have a "toJson" method as well for both, Document and DocumentTree. 

For Document, something like:
```
Map<String, dynamic> toJson() => {
        'uri_string': uriString,
        'name': name,
        'is_virtual': isVirtual,
        'is_directory': isDirectory,
        'file_type': fileType,
        'last_modified': lastModified,
        'file_length': fileLength,
        'is_writable': isWritable,
        'is_deletable': isDeletable
      };
```

For DocumentTree: 
```
Map<String, dynamic> toJson() => {
        'uri_string': uriString,
        'children': children
            .map((doc) => doc.toJson())
            .toList(),
      };
```

Again, thanks a lot for this package!

**Comment by SNNafi** [comment]
Thanks for the concern. But what's the use case of `toJson` in this case?

**Comment by StephanKimmerle** [comment]
I'm using your media_store_plus package to read audio files for an audio playing app. I want to save the state of the app and restart it where I left of: with the same DocumentTree the user has chosen as the basis for selecting audio files and the same Document selected to play, just where the user has left things. I have a data class that neatly captures all of that state, nicely produced with the freezed package that allows me to very easily turn all of that into a json serializable form where I can store it and reload it - including the chosen DocumentTree as root and the selected Document. 
Just your DocumentTree acts a bit weird when using its fromJson method and both, Document and DocumentTree do not have toJson methods. I bypass this with two JsonConverters (I overwrite your DocumentTree fromJson and implement toJson methods there); however, that's not nice :-)
As it takes a while to load a DocumentTree and a Document if you have a let's say larger music folder on your phone, it just speeds up the start of the app, if you can easily save Document and DocumentTree (otherwise you could just save a uriString and rebuild what you need - but that takes time). 

I don't think that's too specific for audio files, but would be similar with apps using photos, videos, etc - I assume.

**Comment by SNNafi** [comment]
Thanks for your clarification. Would you mind giving a PR with the necessary changes?

**Comment by StephanKimmerle** [comment]
OK, I had to learn how to do that :-)
Done.
